server:
  port: 8888
spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_URI}
          default-label: main
          skip-ssl-validation: true
          username: a-dilmen
          password: ${CONFIG_SERVER_TOKEN}